from __future__ import annotations

from .models import RuleMetadata
from .rules import CODE_RULES

RULESET_VERSION = "2026.07.11"


_RULE_OVERRIDES: dict[str, dict[str, object]] = {
    "untrusted-workspace-input-to-process": {
        "title": "Workspace input reaches process execution",
        "category": "execution",
        "evidence_class": "correlated",
        "default_severity": "HIGH",
        "description": "Semgrep taint analysis found workspace-controlled data reaching a process execution sink.",
        "recommendation": "Require explicit user initiation and pass validated arguments without shell interpolation.",
        "benchmark_tags": ["semgrep", "workspace", "execution"],
    },
    "webview-message-to-process": {
        "title": "Webview message reaches execution",
        "category": "webview",
        "evidence_class": "correlated",
        "default_severity": "HIGH",
        "description": "Semgrep taint analysis found webview-controlled message data reaching an execution sink.",
        "recommendation": "Validate message schemas and keep webview data away from command construction.",
        "benchmark_tags": ["semgrep", "webview", "execution"],
    },
    "decoded-payload-execution": {
        "title": "Decoded payload reaches dynamic execution",
        "category": "code",
        "evidence_class": "correlated",
        "default_severity": "HIGH",
        "description": "Semgrep found decoded or deobfuscated data flowing into dynamic execution.",
        "recommendation": "Remove dynamic payload execution or make the decoded artifact immutable and verifiable.",
        "benchmark_tags": ["semgrep", "obfuscation", "execution"],
    },
    "unicode-evasion": {
        "title": "Unicode source-code evasion",
        "category": "code",
        "evidence_class": "weak",
        "default_severity": "MEDIUM",
        "description": "YARA matched bidirectional or invisible Unicode control bytes.",
        "recommendation": "Inspect the matched bytes and remove invisible controls from executable files.",
        "benchmark_tags": ["yara", "unicode", "evasion"],
    },
    "encoded-dynamic-execution": {
        "title": "Encoded dynamic execution",
        "category": "code",
        "evidence_class": "correlated",
        "default_severity": "HIGH",
        "description": "YARA matched encoded payload handling combined with dynamic execution markers.",
        "recommendation": "Inspect the decoded payload and block the artifact when its origin cannot be verified.",
        "benchmark_tags": ["yara", "obfuscation", "execution"],
    },
    "embedded-pe-artifact": {
        "title": "Embedded portable executable",
        "category": "artifact",
        "evidence_class": "provenance",
        "default_severity": "MEDIUM",
        "description": "YARA found portable executable content embedded inside another artifact.",
        "recommendation": "Extract, hash, sign, and independently inspect the embedded executable.",
        "benchmark_tags": ["yara", "binary", "provenance"],
    },
    "credential-exfiltration-chain": {
        "title": "Credential exfiltration chain",
        "category": "credential-access",
        "evidence_class": "correlated",
        "default_severity": "HIGH",
        "description": "Detects code paths combining credential references, local file reads, and outbound transfer.",
        "recommendation": "Review source and remove the extension if behavior is unexpected.",
        "false_positive_notes": "May trigger on legitimate cloud tooling or credential helpers.",
        "benchmark_tags": ["credential", "filesystem", "network"],
    },
    "agent-data-exfil-chain": {
        "title": "Agent data exfiltration chain",
        "category": "agentic",
        "evidence_class": "correlated",
        "default_severity": "HIGH",
        "description": "Detects agent-facing code combined with sensitive references and outbound network behavior.",
        "recommendation": "Review agent tool boundaries and approval prompts before trusting the extension.",
        "benchmark_tags": ["agentic", "credential", "network"],
    },
    "download-and-execute": {
        "title": "Download and execute",
        "category": "execution",
        "evidence_class": "correlated",
        "default_severity": "HIGH",
        "description": "Detects source files that can download content and execute local processes.",
        "recommendation": "Verify download source, integrity checks, and execution purpose.",
        "benchmark_tags": ["download", "execution", "network"],
    },
    "lifecycle-script": {
        "title": "Lifecycle script",
        "category": "supply-chain",
        "evidence_class": "capability",
        "default_severity": "MEDIUM",
        "description": "Package defines install or uninstall lifecycle scripts.",
        "recommendation": "Inspect lifecycle scripts because they execute outside normal extension UI flows.",
        "false_positive_notes": "Many legitimate packages use install scripts to prepare native components.",
        "benchmark_tags": ["supply-chain", "install"],
    },
    "agentic-tooling": {
        "title": "Agent-facing IDE capability",
        "category": "agentic",
        "evidence_class": "capability",
        "default_severity": "MEDIUM",
        "description": "Extension contributes language model tools, chat participants, or MCP server surfaces.",
        "recommendation": "Review tool permissions and approval behavior before trusting agent-facing extensions.",
        "benchmark_tags": ["agentic", "mcp"],
    },
    "native-or-packed-artifact": {
        "title": "Native or packed artifact",
        "category": "artifact",
        "evidence_class": "capability",
        "default_severity": "MEDIUM",
        "description": "Extension package contains native binaries or packed archives.",
        "recommendation": "Confirm binary provenance and inspect packed artifacts before deployment.",
        "benchmark_tags": ["native", "artifact"],
    },
    "known-bad-artifact": {
        "title": "Known-bad artifact",
        "category": "confirmed-intelligence",
        "evidence_class": "confirmed",
        "default_severity": "CRITICAL",
        "description": "Package or file hash matched configured malicious intelligence.",
        "recommendation": "Block or remove this extension.",
        "benchmark_tags": ["confirmed", "hash"],
    },
    "marketplace-removed-package": {
        "title": "Marketplace removed package",
        "category": "provenance",
        "evidence_class": "provenance",
        "default_severity": "HIGH",
        "description": "Extension appears in a marketplace removed package list.",
        "recommendation": "Review removal reason and avoid the extension unless trust is independently established.",
        "benchmark_tags": ["marketplace", "provenance"],
    },
    "malicious-npm-dependency": {
        "title": "Malicious npm dependency",
        "category": "dependency",
        "evidence_class": "confirmed",
        "default_severity": "CRITICAL",
        "description": "Dependency vulnerability intelligence identifies a malicious package.",
        "recommendation": "Remove the extension or replace the affected dependency before use.",
        "benchmark_tags": ["dependency", "malware"],
    },
    "vulnerable-npm-dependency": {
        "title": "Vulnerable npm dependency",
        "category": "dependency",
        "evidence_class": "dependency",
        "default_severity": "HIGH",
        "description": "Dependency vulnerability intelligence reported vulnerable runtime dependencies.",
        "recommendation": "Upgrade or replace the vulnerable dependency.",
        "benchmark_tags": ["dependency", "vulnerability"],
    },
    "safe-configured-cli-execution": {
        "title": "Configured CLI execution",
        "category": "execution",
        "evidence_class": "weak",
        "default_severity": "INFO",
        "description": "Code executes a configured local CLI through execFile-style process execution.",
        "recommendation": "Treat as contextual when the binary path is user-configured and arguments are explicit.",
        "benchmark_tags": ["execution", "cli"],
    },
    "dynamic-shell-execution": {
        "title": "Dynamic shell execution",
        "category": "execution",
        "evidence_class": "capability",
        "default_severity": "MEDIUM",
        "description": "Code uses shell-style process execution.",
        "recommendation": "Review command construction and avoid shell execution for untrusted input.",
        "benchmark_tags": ["execution", "shell"],
    },
    "untrusted-input-execution": {
        "title": "Untrusted input execution",
        "category": "execution",
        "evidence_class": "capability",
        "default_severity": "MEDIUM",
        "description": "Code appears to combine IDE/workspace input with process execution.",
        "recommendation": "Ensure file paths, document content, and workspace values are passed as arguments without shell interpolation.",
        "benchmark_tags": ["execution", "input"],
    },
    "ast-dynamic-call-target": {
        "title": "AST: dynamic call target",
        "category": "execution",
        "evidence_class": "capability",
        "default_severity": "MEDIUM",
        "description": "The AST analyzer found a function call whose target is resolved through computed member access (e.g. obj[x](...)) rather than a literal property name -- a common way to invoke eval/exec-family sinks without the literal token appearing in a plain-text scan.",
        "recommendation": "Inspect what the computed property resolves to at runtime and whether it can be influenced by untrusted input.",
        "false_positive_notes": "Legitimate dynamic dispatch (plugin registries, event handler maps) also matches this pattern; severity escalates to HIGH only when the resolved value names a sensitive sink.",
        "benchmark_tags": ["execution", "ast", "evasion"],
    },
    "ast-bracket-notation-sensitive-access": {
        "title": "AST: bracket-notation access to sensitive global",
        "category": "code",
        "evidence_class": "capability",
        "default_severity": "HIGH",
        "description": "The AST analyzer resolved a bracket-notation member access (e.g. window[\"e\"+\"val\"]) to a sensitive name such as eval, Function, require, or child_process, where the property was built at runtime rather than written as a literal string.",
        "recommendation": "Treat this as a deliberate evasion attempt against plain-text detection and review the surrounding code path closely.",
        "benchmark_tags": ["code", "ast", "evasion", "obfuscation"],
    },
    "ast-constructed-dynamic-argument": {
        "title": "AST: constructed argument to a dynamic sink",
        "category": "code",
        "evidence_class": "capability",
        "default_severity": "HIGH",
        "description": "The AST analyzer found eval/Function/require/exec-family calls whose argument is assembled at runtime (string concatenation or String.fromCharCode) and folds to a suspicious keyword, instead of being passed as a plain string literal.",
        "recommendation": "Review why the executed/required target is not a literal; this is the exact shape used to evade regex-based static analysis.",
        "benchmark_tags": ["code", "ast", "evasion", "obfuscation"],
    },
    "credential-config-key": {
        "title": "Credential configuration key",
        "category": "cross-extension-exposure",
        "evidence_class": "exposure",
        "default_severity": "LOW",
        "description": "Detects configuration keys or descriptions that appear credential-related.",
        "recommendation": "Use SecretStorage or an OS credential store instead of extension-readable configuration for secrets.",
        "false_positive_notes": "Can trigger on documentation, examples, or non-secret uses of key/token terminology.",
        "benchmark_tags": ["credential", "configuration", "cross-extension"],
    },
    "credential-global-state-key": {
        "title": "Credential global state key",
        "category": "cross-extension-exposure",
        "evidence_class": "exposure",
        "default_severity": "LOW",
        "description": "Detects globalState or workspaceState keys that appear credential-related.",
        "recommendation": "Avoid storing credentials in extension state unless access boundaries and lifetime are understood.",
        "benchmark_tags": ["credential", "globalState", "cross-extension"],
    },
    "credential-inputbox-prompt": {
        "title": "Credential InputBox prompt",
        "category": "cross-extension-exposure",
        "evidence_class": "exposure",
        "default_severity": "MEDIUM",
        "description": "Detects InputBox prompts or options that appear to request credentials.",
        "recommendation": "Use explicit secret-entry UX and store captured credentials in SecretStorage.",
        "benchmark_tags": ["credential", "inputBox", "cross-extension"],
    },
    "clipboard-read-near-secret-input": {
        "title": "Clipboard read near secret input",
        "category": "cross-extension-exposure",
        "evidence_class": "correlated",
        "default_severity": "HIGH",
        "description": "Detects clipboard reads near credential-related input or storage surfaces.",
        "recommendation": "Avoid reading clipboard contents around secret capture flows unless the user explicitly requested it.",
        "benchmark_tags": ["credential", "clipboard", "cross-extension"],
    },
    "credential-command-registration": {
        "title": "Credential command registration",
        "category": "cross-extension-exposure",
        "evidence_class": "exposure",
        "default_severity": "LOW",
        "description": "Detects commands whose identifiers or labels appear credential-related.",
        "recommendation": "Ensure credential-related commands require explicit user intent and cannot be abused by another extension.",
        "benchmark_tags": ["credential", "commands", "cross-extension"],
    },
    "credential-command-execution": {
        "title": "Credential command execution",
        "category": "cross-extension-exposure",
        "evidence_class": "exposure",
        "default_severity": "MEDIUM",
        "description": "Detects execution of credential-related VS Code commands.",
        "recommendation": "Review command control paths and avoid allowing untrusted input to steer credential operations.",
        "benchmark_tags": ["credential", "commands", "cross-extension"],
    },
    "credential-command-control": {
        "title": "Credential command control",
        "category": "cross-extension-exposure",
        "evidence_class": "correlated",
        "default_severity": "HIGH",
        "description": "Detects credential-related input near cross-extension command or state-control surfaces.",
        "recommendation": "Manually verify whether another extension can invoke, imitate, or influence the credential flow.",
        "benchmark_tags": ["credential", "commands", "inputBox", "cross-extension"],
    },
    "credential-config-update": {
        "title": "Credential configuration storage",
        "category": "cross-extension-exposure",
        "evidence_class": "exposure",
        "default_severity": "HIGH",
        "description": "Detects writes of credential-related values to VS Code configuration.",
        "recommendation": "Do not store credentials in VS Code settings; use SecretStorage or an OS credential store.",
        "benchmark_tags": ["credential", "configuration", "storage"],
    },
    "credential-global-state-storage": {
        "title": "Credential global state storage",
        "category": "cross-extension-exposure",
        "evidence_class": "exposure",
        "default_severity": "HIGH",
        "description": "Detects writes of credential-related values to globalState or workspaceState.",
        "recommendation": "Avoid storing raw credentials in extension state; use SecretStorage for secret material.",
        "benchmark_tags": ["credential", "globalState", "storage"],
    },
    "credential-dataflow-to-network": {
        "title": "Credential data flow to network",
        "category": "cross-extension-exposure",
        "evidence_class": "correlated",
        "default_severity": "CRITICAL",
        "description": "Detects credential-related source surfaces in a file that also contains network sinks.",
        "recommendation": "Manually verify the data flow. If credential data reaches network sinks unexpectedly, block the extension.",
        "benchmark_tags": ["credential", "network", "dataflow"],
    },
    "credential-dataflow-to-process": {
        "title": "Credential data flow to process",
        "category": "cross-extension-exposure",
        "evidence_class": "correlated",
        "default_severity": "HIGH",
        "description": "Detects credential-related source surfaces in a file that also contains process execution.",
        "recommendation": "Manually verify whether credentials can influence process execution or command arguments.",
        "benchmark_tags": ["credential", "process", "dataflow"],
    },
    "credential-dataflow-to-file": {
        "title": "Credential data flow to file",
        "category": "cross-extension-exposure",
        "evidence_class": "correlated",
        "default_severity": "HIGH",
        "description": "Detects credential-related source surfaces in a file that also contains file writes.",
        "recommendation": "Review file persistence paths and ensure raw secrets are not written to workspace or extension files.",
        "benchmark_tags": ["credential", "filesystem", "dataflow"],
    },
}


def rule_registry() -> list[RuleMetadata]:
    rules: dict[str, RuleMetadata] = {}
    for rule in CODE_RULES:
        rules[rule.id] = RuleMetadata(
            rule_id=rule.id,
            title=_title(rule.id),
            category=rule.category,
            evidence_class="weak",
            default_severity=rule.severity,  # type: ignore[arg-type]
            description=rule.summary,
            recommendation="Treat this as review evidence unless it combines with credential, network, download, or destructive behavior.",
            benchmark_tags=[rule.category],
        )

    for rule_id, override in _RULE_OVERRIDES.items():
        rules[rule_id] = RuleMetadata(
            rule_id=rule_id,
            title=str(override["title"]),
            category=str(override["category"]),
            evidence_class=str(override["evidence_class"]),
            default_severity=str(override["default_severity"]),  # type: ignore[arg-type]
            description=str(override["description"]),
            recommendation=str(override["recommendation"]),
            false_positive_notes=str(override.get("false_positive_notes") or ""),
            benchmark_tags=list(override.get("benchmark_tags") or []),
        )
    return sorted(rules.values(), key=lambda item: item.rule_id)


def rules_json() -> dict[str, object]:
    return {
        "ruleset_version": RULESET_VERSION,
        "rules": [rule.to_dict() for rule in rule_registry()],
    }


def _title(rule_id: str) -> str:
    return rule_id.replace("-", " ").replace(":", ": ").title()
